/*									*/
/*	Automagically generated by DATA2ARRAY-04-30-2001-15:36:02	*/
/*		DO NOT ATTEMPT TO MODIFY THIS FILE			*/
/*									*/

 uint bsort_input[] =\
{
	 5,10,7,14,9,16,6,19,20,13,8,11,3,12,18,2,15,1,17,4
};

const int bsort_input_len = 20;
